---
#Shared Variables
aws_region: us-west-2
vpc_prefix: ACIT4640

#VPC Variables
vpc_cidr: 10.46.0.0/16

#Subnet Variab;es
aws_zone: us-west-2a
vpc_subnet_cidr: 10.46.10.0/24

#Security Group Variables
secgroup_desc: port 22 and port 80 access
secgroup_ssh_instructor_cidr: 0.0.0.0/0

#EC2 Variables
ami_id: ami-01ed306a12b7d1c96
ec2_name: ACIT4640_Final
ec2_type: t2.micro
aws_key_name: ACIT4640_key 

