---
- name: Creating the EC2 machine
  ec2: 
    region: "{{ aws_region }}"
    image: "{{ ami_id }}"
    exact_count: 1
    count_tag:
      Name: "{{ ec2_name }}"
    instance_type: "{{ ec2_type }}"
    instance_tags:
      Name: "{{ ec2_name }}"
    key_name: "{{ aws_key_name }}"
    vpc_subnet_id: "{{ subnet_data.subnet.id }}"
    group_id: "{{ secgroup_data.group_id }}"
    volumes:
      - device_name: /dev/sda1
        delete_on_termination: true
        volume_size: 8
    wait: true
  tags:
    - provision
  register: ec2_data

- name: Grabbing and Gathering the EC2 instance info
  ec2_instance_facts:
    region: "{{ aws_region }}"
    filters:
     "tag:Name": "{{ ec2_name }}"
     instance-state-name: running
  tags:
    - provision
  register: ec2_facts

- name: Creating Elastic IP
  ec2_eip:
    state: present
    region: "{{ aws_region }}"
    in_vpc: true
    reuse_existing_ip_allowed: "yes"
    release_on_disassociation: "yes"
    device_id: "{{ ec2_data.tagged_instances[0].id }}"
  tags:
    - provision
  register: eip_data

- name: Elastic IP display
  debug: 
    msg: "Elastic IP created: {{ eip_data.public_ip }}"
  tags:
    - provision

- name: Checking for connection to EC2 machine...
  wait_for_connection:
    delay: 60
    timeout: 300
  tags:
    - provision    
